# Generated by Django 4.0 on 2022-09-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
