# Generated by Django 4.0 on 2022-09-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0003_user_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='exam',
        ),
    ]
