# Generated by Django 4.0 on 2022-09-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0004_rename_city_user_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='mark',
        ),
    ]
