# Generated by Django 4.0 on 2022-09-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0005_rename_age_user_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mark',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='exam',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to='sql.User')),
            ],
        ),
    ]
