# Generated by Django 4.0 on 2022-09-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0006_rename_mark_user_age_remove_user_exam_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='users',
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='exams',
            field=models.ManyToManyField(to='sql.Exam'),
        ),
    ]
