# Generated by Django 4.0 on 2022-09-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0007_remove_exam_users_exam_name_user_exams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='exams',
            new_name='exam',
        ),
    ]
